### ISSUE TITLE
USER STORY: Configure Admin Site 

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/postit#12]
As a **developer**, I can **configure the admin site**, so that **I can have greater control and functionality than the default settings.**

## Tasks
- [x] Task 1 - Import and impplement Django Summernote 
- [x] Task 2 - Customize the Postit model with Django admin classes
- [x] Task 3 - Customise Category model with Django admin classes
- [x] Task 4 - Customise the Comments model with Django admin classes and add approved comments functionality 
- [x] Task 5 - Customise the Reply model with Django admin classes and add approved comments functionality
