### ISSUE TITLE
USER STORY: Navigation Menu & Footer 

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/postit#14]
As a **user**, I can **use the navigation bar and footer**, so that **I can look at the sites pages, features, and content and learn more about Postit through their social media and contact information**

## Tasks
- [x] Task 1 - Create logo 
- [x] Task 2 - Create Site Navigation Menu 
- [x] Task 3 - Create Call To Action Button 
- [x] Task 4 - Include Socials & Contact Information
- [x] Task 5 - Link View For Base.html to Forum & Postit urls.py files
