### ISSUE TITLE
USER STORY: Build the home page where the latest posts will be featured 

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/postit#19]
As a **user**, I can **read and search through the home page**, so that **I can sift through posts I want to look at in more detail and then comment on **

## Tasks
- [x] Task 1 - Create a home page in terms of layout and styling which will house the posts/threads so that users can read through them
- [x] Task 2 - Create each individual postit which will contain a summary of the post
- [x] Task 3 - Organise and prioritise the information in each summary post 
- [x] Task 4 - Create the view and url that will render the said posts 
- [x] Task 5 - In the view use the user id and slug fields to render a detailed view of the post that was clicked on and categorise the posts from the date they were uploaded
