### ISSUE TITLE
USER STORY: Django Setup 

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/postit#2]
As a **developer**, I can **I want to install Django and  the supporting libraries  required**, so that **I can start developing POSTIT**

## Tasks
- [ ] Task 1 - Install Django & gunicorn 
- [ ] Task 2 - Install dj_database_url & psycopg2 
- [ ] Task 3 - Install dj3-cloudinary-storage
- [ ] Task 4 - Create a requirements.txt file 
- [ ] Task 4 - Create the project directory - postit 
- [ ] Task 5 - Create the app directory forum and add it to the installed apps list in the settings.py file within the postit directory
