### ISSUE TITLE
USER STORY: Install Django & Dependencies

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/postit#2]
As a **developer**, I can **download Django & other libraries**, so that **I have my Django app and project setup as well as the database and third-party software ready to begin coding **

## Tasks
- [x] Task 1 - Install Django & gunicorn 
- [x] Task 2 - Install PostgreSQL & setup database & migrations
- [x] Task 3 - Install cloudinary 
- [x] Task 4 - Create Django project and app directories
