### ISSUE TITLE
USER STORY: Build The Create Post Page & Functionality 

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/postit#20]
As a **user**, I can **head to the create post section of Postit**, so that **I can start creating posts which I can showcase to other users and engage with a wider community **

## Tasks
- [x] Task 1 - Build the create post page in terms of layout and styling 
- [x] Task 2 - Create a form using Django that will allow users to post their ideas which will be rendered on the home page 
- [x] Task 3 - Create the view and link the url
