### ISSUE TITLE
USER STORY: Create the Full  Thread Page & Commenting System 

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/postit#21]
As a **user**, I can **click a post that I find interesting on the home page**, so that **I will be redirected to a more detailed view of the Post and can comment underneath it**

## Tasks
- [x] Task 1 - Build the layout and styling of the full thread page
- [x] Task 2 - Create a commenting Django form that will share the user's thoughts
- [x] Task 3 - Create the view and link the url so that it will render the correct post that is clicked on 
- [x] Task 4 - Add the original view so that users can comment on posts.
