### ISSUE TITLE
USER STORY: Build The Profile Page That Will Store The Users Posts 

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/postit#22]
As a **user**, I can **access my own profile page**, so that **I can look at my historical posts and update or delete ones I am interested in**

## Tasks
- [x] Task 1 - Create the layout and styling for the profile page
- [x] Task 2 - Add functionality that will showcase the relevant users name and order posts from newest to oldest 
- [x] Task 3 - Create the view and link the url to do so
- [x] Task 4 - Create an update and delete button that will allow the user to organise their posts 
- [x] Task 5 - Create the view and link the url
