### ISSUE TITLE
USER STORY: Give Users The Ability to Create Accounts Or Log Back Into Postit

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/postit#24]
As a **user**, I can **create, log in and out of postit**, so that **I can access extra features and keep my posts safe**

## Tasks
- [x] Task 1 - Install Aullauth
- [x] Task 2 - Utilise their batteries included  account management forms 
- [x] Task 3 - Style and link the forms to Postit 
- [x] Task 4 - Based on the user's account and logged status give them access to extra features or stop them from accessing said features
