### ISSUE TITLE
USER STORY: Setup Files & Folders 

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/postit#3]
As a **developer**, I can **setup and configure my files and folders **, so that ** I have a structured workspace and all dependencies are connected properly **

## Tasks
- [x] Task 1 - Create env.py file and environment variables 
- [x] Task 2 - Create requirements.txt file and include any files you want hidden 
- [x] Task 3 - Create Procfile 
- [x] Task 4 - Create media, static and template directories 
- [x] Task 5 - Configure settings.py file with newley added dependencies and environment varaibles
