### ISSUE TITLE
USER STORY: Heroku & Further Workspace Setup

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/postit#3]
As a **developer**, I can **setup the project workspace even further**, so that **I can begin to expand on its current functionality**

## Tasks
- [ ] Task 1 - Create Heroku app for POST IT & add Postgres database
- [ ] Task 2 - Create env.py file aswell as adding the DATABASE_URL & SECRET_KEY environment variables 
- [ ] Task 3 - Configure settings.py by importing os and the database if os path is env.py
- [ ] Task 4 - Configure settings.py by adding environment variables of SECRET_KEY and DATABASE_URL
