### ISSUE TITLE
USER STORY: Create & Deploy App In Heroku 

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/postit#4]
As a **developer**, I can **create my Heroku app, database and config vars**, so that **deploy my project early on Heroku**

## Tasks
- [x] Task 1 - Create Heroku app
- [x] Task 2 - Add Heroku Postgres Database 
- [x] Task 3 - Update Config Vars 
- [x] Task 4 - Install Heroku & link GitHub repository to Heroku using the CLI 
- [x] Task 5 - Deploy project
