### ISSUE TITLE
USER STORY: Create Postit Model 

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/postit#6]
As a **developer**, I can **create the Postit model**, so that **users can create posts on my site**

## Tasks
- [x] Task 1 - Create the name and type columns and their respective row values within the Postit model
- [x] Task 2 - Create helper Metaclasses to order Posts in descending manner
- [x] Task 3 - Create str methods for each model
