### ISSUE TITLE
USER STORY: Create Category Model

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/postit#7]
As a **developer**, I can **create the Categories model**, so that **the user can tag which category their post belongs to**

## Tasks
- [x] Task 1 - Create a name and type columns as well as their value row
- [x] Task 2 - Connect the category row within the Categories modal to the Postit modal topic row using a Many To Many relationships
- [x] Task 3 - Create a str method
