### ISSUE TITLE
USER STORY: Create Comments Model 

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/postit#8]
As a **developer**, I can **create the Comments Model**, so that **users can share their thoughts on a post **

## Tasks
- [x] Task 1 - Create Comments models rows and columns 
- [x] Task 2 - Create a foreign key relationship between the postit and user models 
- [x] Task 3 - Create a replies row which will have a many to many relationships with a Reply model 
- [x] Task 4 - Create a Meta class ordering the comments in ascending order 
- [x] Task 5 - Return string method of comment and username
